# Generated by Django 3.1 on 2021-08-11 10:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_rewiewrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RewiewRating',
            new_name='ReviewRating',
        ),
    ]
