# Generated by Django 3.1 on 2021-08-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgalery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgalery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
